### PR TITLE
Fix ES locale entry ("Homepage")

### PR DESCRIPTION
**Pull request by megatux**
Changed "Inicio" because it could be misunderstood.

### CODE REVIEW

**Comment by donadigo** [comment]
Can someone comment which is more appropriate here?

**Comment by waldyrious** [comment]
@donadigo _"Inicio"_ means "start" or "beginning". _"Página principal"_ means "main page" and is commonly used as a translation for "Homepage".

If this is meant to refer to the link provided [here](https://github.com/donadigo/eddy/blob/bcfe065c470ea73ea16fbb2bb26c8f76ff75d430/data/com.github.donadigo.eddy.appdata.xml#L219), then indeed _"Página principal"_ would work better than _"Inicio"_ (or maybe even _"Página web"_ for "webpage", or _"Sitio web"_ for "website").

**Comment by megatux** [comment]
So, any updates?

**Comment by waldyrious** [comment]
@megatux what are your thoughts about using "Página web" or "Sitio web"?

**Comment by megatux** [comment]
Yes, any of those is correct. I slightly prefer the latter. Updating the branch.

**Pull request merged**
