### PR TITLE
Make metadata files translatable

### LINKED ISSUE #69: Add appdata to be translated
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

### PR DESCRIPTION
**Pull request by ryonakano**
Fixes #69

~After merging this PR, please generate po files for the `extra` namespace. I excluded them from this PR to make it simple.~
However, `extra/lt.po`, `extra/pt_BR.po`, and `extra/cs.po` are included in this PR, because these language has translated strings in the appdata.xml file, and I need to move them into each po files.

### CODE REVIEW

**Comment by ryonakano** [comment]
@donadigo This PR seems to be closed accidentally due to the "fix" keyword in #74, but I have no permission to reopen it. Could you reopen this and review/merge?

**Comment by ryonakano** [comment]
@donadigo Thank you for reopening this! Now the CI passes and it's ready to go

**Comment by donadigo** [comment]
Any reason this was closed?

**Comment by ryonakano** [comment]
@donadigo because I felt this PR would not seem to be merged soon due to inactivity. I'll create a new PR for this.

**Pull request closed without merging**
